- hosts: all
  tasks:
   - name: "Create a file if it does not exist"
     command: "touch /tmp/latestfile"
     args:
       creates: "/tmp/latestfile"
     register: createif
  
   - name: System Uptime
     shell: |
       uptime > /tmp/latestfile 2>&1
       cat /tmp/latestfile
     register: uptime 
   - debug: msg="{{ uptime.stdout }}"
   
   - name: System Uptime
     shell: |
       free > /tmp/latestfile 2>&1
       cat /tmp/latestfile
     register: free
   - debug: msg="{{ free.stdout }}" 
  

