---
- name: "Update an entry into /etc/resolv.conf" 
  hosts: all
  become: true
  gather_facts: true 
  tasks:
   - name: "Execute shell commands"
      shell: 
      command_to_run:
                     Ifconfig
                     uname -a
   - lineinfile:
            line: "nameserver 10.1.250.110"
            path: /etc/resolv.conf
  