- hosts: all
  tasks:
   - name: "Create a file if it does not exist"
     command: "touch /tmp/latestfile"
     args:
       creates: "/tmp/latestfile"
     register: createif
  
   - name: System Uptime
     shell: |
       uptime > /tmp/latestfile 2>&1
       cat /tmp/latestfile
       uname -a > /tmp/latestfile 2>&1
     register: uptime 
     register: uname -a
   - debug: msg="{{ uptime.stdout }}"
   - debug: msg="{{ uname -a.stdout }}"

